"use client";

import { MailCheck, Clock, Sparkles, FileText } from "lucide-react";

export default function AIFollowUpEmailsPage() {
  const ctaLabel = "Generate Follow-Up Emails";

  const updateCtaUrl = (basePath: string, label: string) => {
    if (typeof window === "undefined") return;
    const slug = label.trim().replace(/\s+/g, "-");
    const isCanada = window.location.pathname.startsWith("/en-ca");
    const normalizedBase = isCanada ? `/en-ca${basePath}` : basePath;
    const newUrl = `${normalizedBase}/${slug}`;
    window.history.pushState({}, "", newUrl);
    window.dispatchEvent(new CustomEvent("showStrategyCallCard"));
  };

  return (
    <div className="bg-[#fff7f2] text-slate-900 min-h-screen">
      <main className="mt-0">
        {/* HERO */}
        <section className="bg-gradient-to-b from-[#fff0e6] via-[#fff7f2] to-white min-h-[70vh] flex items-center">
          <div className="max-w-6xl mx-auto px-4 md:px-6 w-full">
            <div className="grid md:grid-cols-2 gap-10 items-center">
              {/* LEFT */}
              <div className="max-w-xl">
                <span className="inline-flex items-center rounded-full bg-[#ffe7d7] px-4 py-1 text-xs md:text-sm font-semibold text-[#ff4c00]">
                  AI Follow-Up Email Generator
                </span>
                <h1 className="mt-4 text-3xl md:text-4xl lg:text-5xl font-extrabold leading-tight">
                  Turn silent applications
                  <span className="block text-[#ff4c00]">
                    into real conversations
                  </span>
                </h1>
                <p className="mt-4 text-sm md:text-base text-slate-700">
                  Flashfire helps you send timely, professional follow‑up emails after
                  job applications and interviews—without sounding robotic or pushy.
                </p>

                <div className="mt-6 space-y-2 text-sm md:text-base">
                  <div className="flex items-center gap-2">
                    <MailCheck className="h-4 w-4 text-[#ff4c00]" />
                    <span>Role-specific follow-ups for each opportunity</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4 text-[#ff4c00]" />
                    <span>Timing suggestions so you follow up at the right moment</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-[#ff4c00]" />
                    <span>Human-sounding tone that respects recruiters&apos; time</span>
                  </div>
                </div>

                <div className="mt-8">
                  <button
                    type="button"
                    onClick={() => updateCtaUrl("/ai-follow-up-email-generator", ctaLabel)}
                    className="inline-flex items-center rounded-lg bg-[#ff4c00] px-6 py-3 text-sm font-semibold text-white hover:bg-[#e24400] transition"
                  >
                    {ctaLabel}
                  </button>
                </div>
              </div>

              {/* RIGHT */}
              <div className="relative">
                <div className="rounded-2xl border border-slate-200 bg-white p-7 shadow-md">
                  <p className="text-xs font-semibold text-slate-800 mb-3">
                    Follow‑up preview
                  </p>
                  <div className="rounded-xl bg-[#fff7f2] border border-[#ffd6c2] p-5 space-y-3 text-xs text-slate-700">
                    <p className="font-semibold">Subject: Quick follow‑up on my application</p>
                    <p>
                      Hi [Recruiter Name], I hope you&apos;re doing well. I&apos;m writing to follow up
                      on my application for the{" "}
                      <span className="font-semibold">Frontend Engineer</span> role we discussed last week.
                    </p>
                    <p>
                      I remain very excited about the opportunity to contribute to your team and would
                      be happy to share any additional details or examples of my work that could help
                      with your decision.
                    </p>
                    <p>
                      If the role is already in later stages, I&apos;d still appreciate any feedback you can
                      share so I can improve my profile for similar positions in the future.
                    </p>
                    <p className="text-slate-500">— Generated by Flashfire</p>
                  </div>
                </div>
                <div className="absolute -top-6 -right-6 h-24 w-24 rounded-full bg-[#ffe7d7] blur-2xl -z-10" />
              </div>
            </div>
          </div>
        </section>

        {/* BENEFITS */}
        {/* BENEFITS */}
<section className="relative bg-white py-24 overflow-hidden">
  <div className="absolute top-0 left-1/2 -translate-x-1/2 h-40 w-40 bg-[#ffe7d7] blur-3xl rounded-full opacity-60" />

  <div className="max-w-6xl mx-auto px-4 md:px-6 relative">
    <div className="text-center max-w-2xl mx-auto">
      <h2 className="text-3xl md:text-4xl font-extrabold">
        Why Smart Candidates
        <span className="block text-[#ff4c00]">Always Follow Up</span>
      </h2>
      <p className="mt-4 text-slate-600 text-sm md:text-base">
        Most applicants stop after applying. 
        The ones who follow up strategically get remembered.
      </p>
    </div>

    <div className="mt-16 grid md:grid-cols-3 gap-10">

      <div className="group bg-[#fffaf7] border border-[#ffd6c2] rounded-2xl p-8 hover:shadow-xl transition duration-300">
        <div className="h-14 w-14 flex items-center justify-center rounded-xl bg-[#ffe7d7] text-[#ff4c00] mb-6">
          <MailCheck size={24} />
        </div>
        <h3 className="text-lg font-semibold">
          Stay Top of Mind
        </h3>
        <p className="mt-3 text-sm text-slate-600">
          Recruiters review dozens of profiles daily. 
          A smart follow-up keeps your name visible at the right time.
        </p>
      </div>

      <div className="group bg-[#fffaf7] border border-[#ffd6c2] rounded-2xl p-8 hover:shadow-xl transition duration-300">
        <div className="h-14 w-14 flex items-center justify-center rounded-xl bg-[#ffe7d7] text-[#ff4c00] mb-6">
          <Clock size={24} />
        </div>
        <h3 className="text-lg font-semibold">
          Perfect Timing
        </h3>
        <p className="mt-3 text-sm text-slate-600">
          Know when to follow up after applications or interviews 
          so you don’t look impatient or disappear completely.
        </p>
      </div>

      <div className="group bg-[#fffaf7] border border-[#ffd6c2] rounded-2xl p-8 hover:shadow-xl transition duration-300">
        <div className="h-14 w-14 flex items-center justify-center rounded-xl bg-[#ffe7d7] text-[#ff4c00] mb-6">
          <Sparkles size={24} />
        </div>
        <h3 className="text-lg font-semibold">
          Human, Not Robotic
        </h3>
        <p className="mt-3 text-sm text-slate-600">
          AI-crafted emails that sound thoughtful and confident —
          never generic or overly pushy.
        </p>
      </div>

    </div>
  </div>
</section>
{/* HOW IT WORKS */}
<section className="bg-[#fff7f2] py-24">
  <div className="max-w-6xl mx-auto px-4 md:px-6">

    <div className="text-center max-w-2xl mx-auto">
      <h2 className="text-3xl md:text-4xl font-extrabold">
        How It Works
      </h2>
      <p className="mt-4 text-slate-600 text-sm md:text-base">
        From application to follow-up in under 2 minutes.
      </p>
    </div>

    <div className="mt-16 grid md:grid-cols-3 gap-8 relative">

      {/* Step 1 */}
      <div className="relative bg-white rounded-2xl p-8 border border-[#ffd6c2] shadow-sm hover:shadow-lg transition">
        <span className="absolute -top-4 left-6 bg-[#ff4c00] text-white text-xs font-semibold px-3 py-1 rounded-full">
          STEP 1
        </span>
        <FileText className="text-[#ff4c00] mb-4" size={28} />
        <h3 className="font-semibold text-lg">
          Enter Role Details
        </h3>
        <p className="mt-3 text-sm text-slate-600">
          Add job title, company name, and stage of your application 
          or interview.
        </p>
      </div>

      {/* Step 2 */}
      <div className="relative bg-white rounded-2xl p-8 border border-[#ffd6c2] shadow-sm hover:shadow-lg transition">
        <span className="absolute -top-4 left-6 bg-[#ff4c00] text-white text-xs font-semibold px-3 py-1 rounded-full">
          STEP 2
        </span>
        <Sparkles className="text-[#ff4c00] mb-4" size={28} />
        <h3 className="font-semibold text-lg">
          AI Crafts Your Email
        </h3>
        <p className="mt-3 text-sm text-slate-600">
          The system generates a tailored follow-up 
          with the right tone and structure.
        </p>
      </div>

      {/* Step 3 */}
      <div className="relative bg-white rounded-2xl p-8 border border-[#ffd6c2] shadow-sm hover:shadow-lg transition">
        <span className="absolute -top-4 left-6 bg-[#ff4c00] text-white text-xs font-semibold px-3 py-1 rounded-full">
          STEP 3
        </span>
        <MailCheck className="text-[#ff4c00] mb-4" size={28} />
        <h3 className="font-semibold text-lg">
          Send With Confidence
        </h3>
        <p className="mt-3 text-sm text-slate-600">
          Copy, personalize slightly if needed, and send —
          professionally and confidently.
        </p>
      </div>

    </div>

  </div>
</section>

      </main>
    </div>
  );
}

