"use client";

import { MailCheck, Clock, Sparkles, FileText, Mail } from "lucide-react";
import { FaPlus, FaTimes } from "react-icons/fa";
import { useState } from "react";

export default function AIFollowUpEmailsPage() {
  const ctaLabel = "Generate Follow-Up Emails";
  const [activeFaqIndex, setActiveFaqIndex] = useState<number | null>(null);

  const updateCtaUrl = (basePath: string, label: string) => {
    if (typeof window === "undefined") return;
    const slug = label.trim().replace(/\s+/g, "-");
    const isCanada = window.location.pathname.startsWith("/en-ca");
    const normalizedBase = isCanada ? `/en-ca${basePath}` : basePath;
    const newUrl = `${normalizedBase}/${slug}`;
    window.history.pushState({}, "", newUrl);
    window.dispatchEvent(new CustomEvent("showStrategyCallCard"));
  };

  return (
    <div className="bg-[#fff7f2] text-slate-900 min-h-screen">
      <main className="mt-0">
        {/* HERO */}
        <section className="bg-gradient-to-b from-[#fff0e6] via-[#fff7f2] to-white min-h-[70vh] flex items-center">
          <div className="max-w-6xl mx-auto px-4 md:px-6 w-full">
            <div className="grid md:grid-cols-2 gap-10 items-center">
              {/* LEFT */}
              <div className="max-w-xl">
                <span className="inline-flex items-center rounded-full bg-[#ffe7d7] px-4 py-1 text-xs md:text-sm font-semibold text-[#ff4c00]">
                  AI Follow-Up Email Generator
                </span>
                <h1 className="mt-4 text-3xl md:text-4xl lg:text-5xl font-extrabold leading-tight">
                  Turn silent applications
                  <span className="block text-[#ff4c00]">
                    into real conversations
                  </span>
                </h1>
                <p className="mt-4 text-sm md:text-base text-slate-700">
                  Flashfire helps you send timely, professional follow‑up emails after
                  job applications and interviews—without sounding robotic or pushy.
                </p>

                <div className="mt-6 space-y-2 text-sm md:text-base">
                  <div className="flex items-center gap-2">
                    <MailCheck className="h-4 w-4 text-[#ff4c00]" />
                    <span>Role-specific follow-ups for each opportunity</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4 text-[#ff4c00]" />
                    <span>Timing suggestions so you follow up at the right moment</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-[#ff4c00]" />
                    <span>Human-sounding tone that respects recruiters&apos; time</span>
                  </div>
                </div>

                <div className="mt-8">
                  <button
                    type="button"
                    onClick={() => updateCtaUrl("/ai-follow-up-email-generator", ctaLabel)}
                    className="inline-flex items-center rounded-lg bg-[#ff4c00] px-6 py-3 text-sm font-semibold text-white hover:bg-[#e24400] transition"
                  >
                    {ctaLabel}
                  </button>
                </div>
              </div>

              {/* RIGHT */}
              <div className="relative">
                <div className="rounded-2xl border border-slate-200 bg-white p-7 shadow-md">
                  <p className="text-xs font-semibold text-slate-800 mb-3">
                    Follow‑up preview
                  </p>
                  <div className="rounded-xl bg-[#fff7f2] border border-[#ffd6c2] p-5 space-y-3 text-xs text-slate-700">
                    <p className="font-semibold">Subject: Quick follow‑up on my application</p>
                    <p>
                      Hi [Recruiter Name], I hope you&apos;re doing well. I&apos;m writing to follow up
                      on my application for the{" "}
                      <span className="font-semibold">Frontend Engineer</span> role we discussed last week.
                    </p>
                    <p>
                      I remain very excited about the opportunity to contribute to your team and would
                      be happy to share any additional details or examples of my work that could help
                      with your decision.
                    </p>
                    <p>
                      If the role is already in later stages, I&apos;d still appreciate any feedback you can
                      share so I can improve my profile for similar positions in the future.
                    </p>
                    <p className="text-slate-500">— Generated by Flashfire</p>
                  </div>
                </div>
                <div className="absolute -top-6 -right-6 h-24 w-24 rounded-full bg-[#ffe7d7] blur-2xl -z-10" />
              </div>
            </div>
          </div>
        </section>

        {/* BENEFITS */}
        {/* BENEFITS */}
<section className="relative bg-white py-24 overflow-hidden">
  <div className="absolute top-0 left-1/2 -translate-x-1/2 h-40 w-40 bg-[#ffe7d7] blur-3xl rounded-full opacity-60" />

  <div className="max-w-6xl mx-auto px-4 md:px-6 relative">
    <div className="text-center max-w-2xl mx-auto">
      <h2 className="text-3xl md:text-4xl font-extrabold">
        Why Smart Candidates
        <span className="block text-[#ff4c00]">Always Follow Up</span>
      </h2>
      <p className="mt-4 text-slate-600 text-sm md:text-base">
        Most applicants stop after applying. 
        The ones who follow up strategically get remembered.
      </p>
    </div>

    <div className="mt-16 grid md:grid-cols-3 gap-10">

      <div className="group bg-[#fffaf7] border border-[#ffd6c2] rounded-2xl p-8 hover:shadow-xl transition duration-300">
        <div className="h-14 w-14 flex items-center justify-center rounded-xl bg-[#ffe7d7] text-[#ff4c00] mb-6">
          <MailCheck size={24} />
        </div>
        <h3 className="text-lg font-semibold">
          Stay Top of Mind
        </h3>
        <p className="mt-3 text-sm text-slate-600">
          Recruiters review dozens of profiles daily. 
          A smart follow-up keeps your name visible at the right time.
        </p>
      </div>

      <div className="group bg-[#fffaf7] border border-[#ffd6c2] rounded-2xl p-8 hover:shadow-xl transition duration-300">
        <div className="h-14 w-14 flex items-center justify-center rounded-xl bg-[#ffe7d7] text-[#ff4c00] mb-6">
          <Clock size={24} />
        </div>
        <h3 className="text-lg font-semibold">
          Perfect Timing
        </h3>
        <p className="mt-3 text-sm text-slate-600">
          Know when to follow up after applications or interviews 
          so you don’t look impatient or disappear completely.
        </p>
      </div>

      <div className="group bg-[#fffaf7] border border-[#ffd6c2] rounded-2xl p-8 hover:shadow-xl transition duration-300">
        <div className="h-14 w-14 flex items-center justify-center rounded-xl bg-[#ffe7d7] text-[#ff4c00] mb-6">
          <Sparkles size={24} />
        </div>
        <h3 className="text-lg font-semibold">
          Human, Not Robotic
        </h3>
        <p className="mt-3 text-sm text-slate-600">
          AI-crafted emails that sound thoughtful and confident —
          never generic or overly pushy.
        </p>
      </div>

    </div>
  </div>
</section>
{/* HOW IT WORKS */}
<section className="bg-[#fff7f2] py-24">
  <div className="max-w-6xl mx-auto px-4 md:px-6">

    <div className="text-center max-w-2xl mx-auto">
      <h2 className="text-3xl md:text-4xl font-extrabold">
        How It Works
      </h2>
      <p className="mt-4 text-slate-600 text-sm md:text-base">
        From application to follow-up in under 2 minutes.
      </p>
    </div>

    <div className="mt-16 grid md:grid-cols-3 gap-8 relative">

      {/* Step 1 */}
      <div className="relative bg-white rounded-2xl p-8 border border-[#ffd6c2] shadow-sm hover:shadow-lg transition">
        <span className="absolute -top-4 left-6 bg-[#ff4c00] text-white text-xs font-semibold px-3 py-1 rounded-full">
          STEP 1
        </span>
        <FileText className="text-[#ff4c00] mb-4" size={28} />
        <h3 className="font-semibold text-lg">
          Enter Role Details
        </h3>
        <p className="mt-3 text-sm text-slate-600">
          Add job title, company name, and stage of your application 
          or interview.
        </p>
      </div>

      {/* Step 2 */}
      <div className="relative bg-white rounded-2xl p-8 border border-[#ffd6c2] shadow-sm hover:shadow-lg transition">
        <span className="absolute -top-4 left-6 bg-[#ff4c00] text-white text-xs font-semibold px-3 py-1 rounded-full">
          STEP 2
        </span>
        <Sparkles className="text-[#ff4c00] mb-4" size={28} />
        <h3 className="font-semibold text-lg">
          AI Crafts Your Email
        </h3>
        <p className="mt-3 text-sm text-slate-600">
          The system generates a tailored follow-up 
          with the right tone and structure.
        </p>
      </div>

      {/* Step 3 */}
      <div className="relative bg-white rounded-2xl p-8 border border-[#ffd6c2] shadow-sm hover:shadow-lg transition">
        <span className="absolute -top-4 left-6 bg-[#ff4c00] text-white text-xs font-semibold px-3 py-1 rounded-full">
          STEP 3
        </span>
        <MailCheck className="text-[#ff4c00] mb-4" size={28} />
        <h3 className="font-semibold text-lg">
          Send With Confidence
        </h3>
        <p className="mt-3 text-sm text-slate-600">
          Copy, personalize slightly if needed, and send —
          professionally and confidently.
        </p>
      </div>

    </div>

  </div>
</section>

        {/* EMAIL EXAMPLES SECTION */}
        <section className="bg-white py-24">
          <div className="max-w-6xl mx-auto px-4 md:px-6">
            <div className="text-center max-w-2xl mx-auto">
              <h2 className="text-3xl md:text-4xl font-extrabold">
                Follow-Up Templates
                <span className="block text-[#ff4c00]">For Every Stage</span>
              </h2>
              <p className="mt-4 text-slate-600 text-sm md:text-base">
                Different situations need different approaches. Flashfire adapts.
              </p>
            </div>

            <div className="mt-16 grid md:grid-cols-3 gap-8">
              {[
                {
                  stage: "Post-Application",
                  timing: "5–7 days after applying",
                  preview: "Following up on my application for [Role] at [Company]. I remain very interested...",
                },
                {
                  stage: "Post-Interview",
                  timing: "24–48 hours after interview",
                  preview: "Thank you for the opportunity to discuss [Role]. I wanted to follow up on...",
                },
                {
                  stage: "Offer Follow-Up",
                  timing: "After receiving offer",
                  preview: "Thank you for the offer! I&apos;m excited about the opportunity. I&apos;d like to discuss...",
                },
              ].map((item) => (
                <div
                  key={item.stage}
                  className="bg-[#fffaf7] border border-[#ffd6c2] rounded-2xl p-6 hover:shadow-lg transition"
                >
                  <div className="flex items-center gap-3 mb-4">
                    <Mail className="h-5 w-5 text-[#ff4c00]" />
                    <h3 className="font-semibold">{item.stage}</h3>
                  </div>
                  <p className="text-xs text-[#ff4c00] font-semibold mb-3">{item.timing}</p>
                  <p className="text-sm text-slate-600 italic">&quot;{item.preview}&quot;</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ SECTION */}
        <section className="bg-[#f9e8e0] py-24">
          <div className="max-w-4xl mx-auto px-4 md:px-6">
            <div className="text-center max-w-2xl mx-auto mb-12">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-extrabold text-slate-900 mb-4">
                Frequently Asked
                <span className="block text-[#ff4c00]">Questions</span>
              </h2>
            </div>

            <div className="bg-white rounded-lg shadow-sm overflow-hidden">
              {[
                {
                  q: "When should I send a follow-up email?",
                  a: "For applications: 5–7 business days after applying. For interviews: within 24–48 hours. Flashfire suggests optimal timing based on the stage and your application date.",
                },
                {
                  q: "Will follow-ups make me look desperate?",
                  a: "Not if done right. Flashfire crafts professional, confident emails that show genuine interest without being pushy. Timing and tone matter.",
                },
                {
                  q: "Can I customize the generated emails?",
                  a: "Absolutely. Use Flashfire&apos;s templates as a starting point, then personalize with specific details about your conversation or the role.",
                },
                {
                  q: "What if I don&apos;t hear back after following up?",
                  a: "One follow-up is usually enough. If there&apos;s no response after 7–10 days, it&apos;s likely the role has moved forward. Flashfire helps you move on strategically.",
                },
              ].map((item, i) => (
                <div
                  key={i}
                  className={`border-b border-gray-200 transition-all ${
                    activeFaqIndex === i ? "bg-[#fff7f3] border-l-4 border-l-[#ff4c00]" : ""
                  }`}
                >
                  <button
                    className="w-full flex items-center justify-between p-6 text-left hover:bg-[#fff7f3] transition-colors"
                    onClick={() => setActiveFaqIndex(activeFaqIndex === i ? null : i)}
                  >
                    <span className={`font-semibold text-lg ${activeFaqIndex === i ? "text-[#ff4c00]" : "text-slate-900"}`}>
                      {item.q}
                    </span>
                    <span className="text-[#ff4c00] shrink-0 ml-4">
                      {activeFaqIndex === i ? <FaTimes /> : <FaPlus />}
                    </span>
                  </button>
                  {activeFaqIndex === i && (
                    <div className="px-6 pb-6 text-slate-600 animate-fadeIn">
                      <p>{item.a}</p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>

      </main>
      <style dangerouslySetInnerHTML={{__html: `
        @keyframes fadeIn {
          from {
            opacity: 0;
            transform: translateY(-0.3rem);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
        .animate-fadeIn {
          animation: fadeIn 0.3s ease;
        }
      `}} />
    </div>
  );
}

